### ISSUE TITLE
Switch repo name to lineageos?

### ISSUE THREAD

**Issue by MTRNord** [stucki/docker-lineageos#14]
As mentioned in the Cyanogenmod Blog their servers will be shutdown by Cyanogen Inc at the End of 2016. Is this repo compatible with the [lineageos ](https://github.com/lineageos) fork?

**Comment by stucki** [comment]
Sure it's compatbile. The project always worked for any other AOSP based ROMs, so it will also work for LineageOS.

I plan to rename the repo, however I will still wait a few days or weeks before I do so...

**Comment by stucki** [comment]
I just renamed the repository to https://github.com/stucki/docker-lineageos. You will need to update your Git remote using `git remote set-url origin https://github.com/stucki/docker-lineageos.git` (or just edit `.git/config`).

There are a few references to the Wiki left which I won't change until the new wiki is in place.
