### ISSUE TITLE
Old Path to /home/cmbuild/prebuilts/

### ISSUE THREAD

**Issue by trigrab** [stucki/docker-lineageos#19]
While building I got an error for a missing standard library. After lots of trial and error I recognized the old path in the error message. Unfortunately I can't post the complete message here right now, cause my build process is just working and I don't want to mess it up. I fixed it by adding the folder /home/cmbuild and set a symlink to /home/build/android/prebuilts/

The error was in the path for gcc arm64. I don't know if it is just for arm64 or not.

I would search for the error, but I have no idea where this false path comes from, because its nowhere in the repository.

**Comment by trigrab** [comment]
I can confirm that. I have done a make clean before. Maybe I have to rebuild the docker container without cache. I try this after I successful build my package. Thanks for the fast reply.

**Comment by trigrab** [comment]
I did `docker build --no-cache` and  now it seems to work. I also cleaned the ccache, but afaik this should not change anything.

**Comment by stucki** [comment]
Thanks for your feedback! Good to hear that it works now.
