### ISSUE TITLE
Docker registry?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [stucki/docker-lineageos#21]
I saw that this docker is not listed anywhere on Docker Hub.

Why don't you consider creating an automated build there?

**Comment by stucki** [comment]
Saw no real need for it. It's a huge image which can be built very easily, don't you think?

**Comment by compuguy** [comment]
@stucki True, but in some situations, like doing a cloud deployment to a Jenkins slave (for say AWS CodeBuild) instance, it requires it to be an actual hosted docker image. I don't know if this docker container would work in that instance, on a headless server, but it would be a neat way to streamline it.

**Comment by stucki** [comment]
Does anyone else see a need for this? Otherwise I suggest that you maintain an image on Docker Hub for yourself.
