### ISSUE TITLE
CyanogenMod Wiki is dead

### ISSUE THREAD

**Issue by harryyoud** [stucki/docker-lineageos#23]
Link to archive.org (https://web.archive.org/web/*/https://wiki.cyanogenmod.org/w/Main_Page) for pages or use an alternative.

**Comment by stucki** [comment]
I'm currently waiting for the LineageOS project to see what they come up with. Most likely, the same Wiki will go live again under a new URL... But I'll leave the issue open and check back in a few days...

**Comment by harryyoud** [comment]
Looks to be up btw. wiki.lineageos.org is slowly populating

**Comment by stucki** [comment]
Done, see #32
