### ISSUE TITLE
Invalid volume spec ":/srv/ccache"

### ISSUE THREAD

**Issue by feicong** [stucki/docker-lineageos#24]
docker: Error response from daemon: Invalid volume spec ":/srv/ccache": Invalid volume specification: ':/srv/ccache'.

**Comment by stucki** [comment]
Hmm, seems like CCACHE is not correctly set in your `run.sh`. What's your operating system?
Can you please check the output of the following commands (run these commands inside the project directory on the host):
- `stat -f %N $(pwd)/ccache`
- `readlink -f $(pwd)/ccache`

As a workaround, you can set CCACHE manually in `run.sh`. Will fix the issue as soon as I got feedback from you.

**Comment by feicong** [comment]
ok, FIXED!

**Comment by stucki** [comment]
Well, what fixed it? We should fix the repo if there's a bug...

**Comment by feicong** [comment]
not a bug, works fine.

**Comment by stucki** [comment]
Ok then.
