### ISSUE TITLE
make failed to build some targets

### ISSUE THREAD

**Issue by feicong** [stucki/docker-lineageos#25]
i have try to build lineageos with docker on macOS 10.11.6。the source tree has alread downloaded on external device. exec ./run.sh and got an error.

Checking build tools versions...
build/core/main.mk:168: ************************************************************
build/core/main.mk:169: You are building on a case-insensitive filesystem.
build/core/main.mk:170: Please move your source tree to a case-sensitive filesystem.
build/core/main.mk:171: ************************************************************
build/core/main.mk:172: *** Case-insensitive filesystems not supported.
build/core/ninja.mk:166: recipe for target '/home/build/android/out/build-cm_hammerhead.ninja' failed
make: *** [/home/build/android/out/build-cm_hammerhead.ninja] Error 1
make: Leaving directory '/home/build/android'

#### make failed to build some targets (02:43 (mm:ss)) ####

how to fix it?

**Comment by stucki** [comment]
Well, your filesystem needs to be case sensitive. Maybe this article helps you: http://apple.stackexchange.com/questions/217915/how-to-create-a-case-sensitive-filesystem-in-10-11-1

Note: If you know what you do, then you can also create a Docker volume for storing the Android project. However, I don't recommend to use a Docker volume for such a huge project (~100 GB). Better store the data on the host like this repo normally does it.

**Comment by feicong** [comment]
OK, copy  the source code to exteral NTFS USB device, it works fine now! thx!
`
ddmbp:docker-lineageos rmbp$ ln -s /Volumes/SAMSUNG/lineageos ./android
ddmbp:docker-lineageos rmbp$ ./run.sh 
build@79662a201010:~/android$ 
build@79662a201010:~/android$ ls
Android.bp  bootstrap.bash  device          ndk              system
Makefile    build          external        packages          toolchain
abi        cache          frameworks      pdk              tools
android    cts            hardware        platform_testing  vendor
art        dalvik          kernel          prebuilts
bionic      developers      libcore          repo
bootable    development    libnativehelper  sdk
build@79662a201010:~/android$ source build/envsetup.sh
including device/generic/mini-emulator-arm64/vendorsetup.sh
including device/generic/mini-emulator-armv7-a-neon/vendorsetup.sh
including device/generic/mini-emulator-x86/vendorsetup.sh
including device/generic/mini-emulator-x86_64/vendorsetup.sh
including device/lge/hammerhead/vendorsetup.sh
including vendor/cm/vendorsetup.sh
including sdk/bash_completion/adb.bash
including vendor/cm/bash_completion/git.bash
including vendor/cm/bash_completion/repo.bash
build@79662a201010:~/android$ ls
Android.bp  bootstrap.bash  device          ndk              system
Makefile    build          external        packages          toolchain
abi        cache          frameworks      pdk              tools
android    cts            hardware        platform_testing  vendor
art        dalvik          kernel          prebuilts
bionic      developers      libcore          repo
bootable    development    libnativehelper  sdk
build@79662a201010:~/android$ echo 'you should see this' > abc ; echo 'not just this twice' > ABC ; cat  abc ABC
you should see this
not just this twice
build@79662a201010:~/android$ ls 
ABC        bionic          developers  libcore          repo
Android.bp  bootable        development  libnativehelper  sdk
Makefile    bootstrap.bash  device      ndk              system
abc        build          external    packages          toolchain
abi        cache          frameworks  pdk              tools
android    cts            hardware    platform_testing  vendor
art        dalvik          kernel      prebuilts
build@79662a201010:~/android$ rm abc ABC
build@79662a201010:~/android$ breakfast hammerhead
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:268: *** No matches for product "lineage_hammerhead".  Stop.
** Warning: 'hammerhead' is using CM-based makefiles. This will be deprecated in the next major release.
Looking for dependencies in device/lge/hammerhead

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
LINEAGE_VERSION=14.1-20170126-UNOFFICIAL-hammerhead
TARGET_PRODUCT=cm_hammerhead
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=krait
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.9.4-moby-x86_64-with-Ubuntu-16.04-xenial
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=NMF26V
OUT_DIR=/home/build/android/out
============================================
build@79662a201010:~/android$ brunch hammerhead
including vendor/cm/vendorsetup.sh
...
`
