### ISSUE TITLE
Document recommendations

### ISSUE THREAD

**Issue by boscogh** [stucki/docker-lineageos#26]
Hi, thank you for this project, it really helps!

maybe it would be useful for those who are pretty new to android and docker,
that repo sync is much faster if it is 'repo sync -c j5'
and also, that if used together with docker under windows 7, i.e. docker under oracle virtual box, then bug in virtual box will not allow to repo sync to complete (even with options), just some bug in network bridge driver of virtialbox. 
in docker for windows on Hyper=V (windows 10) is runs smooth

thank you again for your work, it's great, I use it already almost 2 months

**Comment by stucki** [comment]
Thanks for the info. Do you have any further references about the VirtualBox + Windows 7 bug? Please create a new issue for them...
