### ISSUE TITLE
samsung_klte_make_faild

### ISSUE THREAD

**Issue by chupanoid** [stucki/docker-lineageos#28]
build/core/binary.mk:1253: external/deqp/Android.mk: libdeqp: Unused source files: \
build/core/binary.mk:1253: external/pdfium/third_party/pdfiumbigint.mk: libpdfiumbigint: Unused source files: bigint/BigInteger.cc bigint/BigIntegerUtils.cc bigint/BigUnsigned.cc bigint/BigUnsignedInABase.cc
frameworks/av/camera/cameraserver/Android.mk:18: Target has integrated cameraserver into mediaserver. This is weakening security measures introduced in 7.0
build/core/package_internal.mk:143: Empty argument supplied to find-subdir-assets
find: '/home/build/android/out/target/common/obj/SHARED_LIBRARIES/libwifi-hal-mock_intermediates': No such file or directory
build/core/package_internal.mk:143: Empty argument supplied to find-subdir-assets
No private recovery resources for TARGET_DEVICE klte
build/core/java.mk:334: warning: overriding commands for target `/home/build/android/out/target/common/obj/APPS/Dialer_intermediates/src/src/org/codeaurora/presenceserv/IPresenceService.java'
build/core/java.mk:334: warning: ignoring old commands for target `/home/build/android/out/target/common/obj/APPS/Dialer_intermediates/src/src/org/codeaurora/presenceserv/IPresenceService.java'
build/core/java.mk:334: warning: overriding commands for target `/home/build/android/out/target/common/obj/APPS/Dialer_intermediates/src/src/org/codeaurora/presenceserv/IPresenceServiceCB.java'
build/core/java.mk:334: warning: ignoring old commands for target `/home/build/android/out/target/common/obj/APPS/Dialer_intermediates/src/src/org/codeaurora/presenceserv/IPresenceServiceCB.java'
build/core/base_rules.mk:316: warning: overriding commands for target `/home/build/android/out/target/product/klte/root/res/images/charger/battery_fail.png'
build/core/base_rules.mk:316: warning: ignoring old commands for target `/home/build/android/out/target/product/klte/root/res/images/charger/battery_fail.png'
build/core/Makefile:34: warning: overriding commands for target `/home/build/android/out/target/product/klte/system/etc/clatd.conf'
build/core/base_rules.mk:316: warning: ignoring old commands for target `/home/build/android/out/target/product/klte/system/etc/clatd.conf'
Starting build with ninja
ninja: Entering directory `.'
ninja: error: '/home/build/android/out/target/product/klte/obj/lib/libtime_genoff.so.toc', needed by '/home/build/android/out/target/product/klte/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/LINKED/libandroid_servers.so', missing and no
known rule to make it
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
make: Leaving directory '/home/build/android'

#### make failed to build some targets (29 seconds) ####

**Comment by chupanoid** [comment]
Insert in BroadConfig.mk
`USE_NINJA := false`
continue brunch without ninja

**Comment by stucki** [comment]
Or easier: `apt-get install ninja-build`. I must admit, I didn't know about ninja-build until today. See the website https://ninja-build.org/ for more information.
Need to find out if it is now used by default. In this case, we should add the package to the Dockerfile...

**Comment by stucki** [comment]
Seems like a device specific issue. Closing. Please let me know if I'm wrong... :-)

**Comment by stucki** [comment]
Seems like a device specific issue. Closing. Please let me know if I'm wrong... :-)Seems like a device specific issue. Closing. Please let me know if I'm wrong... :-)
