### ISSUE TITLE
Running image on old docker

### ISSUE THREAD

**Issue by ochorocho** [stucki/docker-lineageos#29]
i had trouble to run the docker image. It failed with
```
Cannot open your terminal '/dev/console' - please check.
```
My setup:
- CentOS release 6.8 (Final)
- Docker version 1.7.1, build 786b29d

To work around this issue i changed the following line in startup.sh
```screen -s /bin/bash```
to
```/bin/bash```

**Comment by stucki** [comment]
I'm not sure if we need to add a fix for an outdated Docker version. Why not just upgrade? Did you check if this fixes the issue?

**Comment by ochorocho** [comment]
Well, updating docker leads to dependency hell. It depends on a newer glibc version and some others.
So updating the system would be the best choice.

**Comment by stucki** [comment]
I guess so. Can we close the issue?

**Comment by ochorocho** [comment]
i'll guess yes, it's only affecting me. thanks for your quick support!

**Comment by stucki** [comment]
You're welcome!
