### ISSUE TITLE
Curl download failed

### ISSUE THREAD

**Issue by ochorocho** [stucki/docker-lineageos#30]
I had trouble downloading some package. Can't remember which one it was. To fix it i add a ~/.curlrc config file with the following entry: `--cipher rsa_rc4_128_sha`

**Comment by stucki** [comment]
Would be good to know which package it was. I'd like to verify this because I think it's an issue on the remote end. I prefer to not restrict the cipher list...

**Comment by ochorocho** [comment]
ok ... i'll try to revert the change and check which package actually failed to download.

**Comment by ochorocho** [comment]
changing ~/.curlrc is not the root of the problem. After a clean build its seems like jack-server is failing due to memory issues. so this is not related to this docker image.

Thanks for your help.
