### ISSUE TITLE
Cannot use ADB inside docker when adb server isn't started with sudo

### ISSUE THREAD

**Issue by Archcry** [stucki/docker-lineageos#43]
When I try to list the adb devices it returns with an error:

```
build@976cd17ce1e8:~/android$ adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached 
????????????    no permissions
```

It turns out that the adb server has to be started with root privileges, the following does work:
```
build@976cd17ce1e8:~/android$ sudo adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
build@976cd17ce1e8:~/android$ adb devices
List of devices attached 
335b3080        unauthorized
```

Unauthorized here is normal because I did not give permission to adb on my phone.

**Comment by Archcry** [comment]
Seems like the udev rules for android need to be installed on the base system in order to work.
This means that this is not an issue with the docker image.

You might want to add this as a warning to the documentation, rules can be found here:
https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules

**Comment by stucki** [comment]
@Archcry Thanks for reporting this. Can you create a pull request with updated README.md which lists the possibilities to run adb inside Docker? See also https://github.com/stucki/docker-lineageos/pull/11#issuecomment-204568794 which explains how it can be run via network...

**Comment by Archcry** [comment]
I am currently on holiday and will be back in three weeks, I can do it then. Unless anyone else is willing to do it sooner.
