### ISSUE TITLE
make: *** No rule to make target 'libsrv_init'

### ISSUE THREAD

**Issue by nekulin** [stucki/docker-lineageos#47]
target thumb C: pppd <= external/ppp/pppd/upap.c
make: *** No rule to make target 'libsrv_init', needed by '/home/build/android/android/out/target/product/maguro/obj/EXECUTABLES/pvrsrvinit_intermediates/pvrsrvinit.o'.  Stop.
make: *** Waiting for unfinished jobs....
target thumb C: pppd <= external/ppp/pppd/utils.c

**Comment by stucki** [comment]
Can you still reproduce this? I don't think it's a problem of the Docker box. Please check your sources!
