### ISSUE TITLE
Any plans to switch to a newer version of Ubuntu?

### ISSUE THREAD

**Issue by ndrewtl** [stucki/docker-lineageos#48]
I noticed this image is still running Ubuntu 16.04 Xenial Xerus. Is this necessary for compatibility? If not, are there any plans to update to a newer version?

**Comment by ontherunvaro** [comment]
If it ain't broke, don't fix it.

**Comment by stucki** [comment]
It doesn't seem to work right now. Just try replacing `FROM: ubuntu:16.04` with `FROM: ubuntu:18.04` in Dockerfile, followed by running `./run.sh --rebuild`.

I think we shouldn't change this until the build reference on https://wiki.lineageos.org/devices/bullhead/build will at least mention Ubuntu 18.04. Right now it looks like everybody is using Ubuntu 16.04 if using Ubuntu at all...
